/**
 * 世界の鳥クイズのデータ定義
 *
 * BIRDS: 出題対象であり、選択肢の母集団でもある。1種＝1問。
 *        選択肢は毎問ここから10個を選び直すので、設問ごとに顔ぶれが変わる。
 *
 * group   同じ値どうしは「似た仲間」として、選択肢に優先的に混ぜる。
 *         分類学的な厳密さより、見た目・暮らしの近さで括ってある。
 * taxon   表示用の正確な分類（目・科）。
 * image   URL / 相対パス（例: "images/tancho.jpg"）を書くと最優先で使う。
 *         空なら wiki.ja → wiki.en の順に Wikipedia の REST API から代表画像を取る。
 */

const GROUPS = [
  { id: 'ratite',    label: '走鳥類' },
  { id: 'ground',    label: '地上を歩く鳥' },
  { id: 'waterfowl', label: 'カモ・ハクチョウの仲間' },
  { id: 'penguin',   label: 'ペンギン' },
  { id: 'seabird',   label: '海鳥' },
  { id: 'wader',     label: '水辺の大型鳥' },
  { id: 'raptor',    label: '猛禽類' },
  { id: 'owl',       label: 'フクロウ類' },
  { id: 'parrot',    label: 'インコ・オウム類' },
  { id: 'colorful',  label: '森の色鳥' },
  { id: 'songbird',  label: 'スズメ目の鳥' },
];

const BIRDS = [
  // ── 走鳥類 ────────────────────────────────────────────
  {
    id: 'ostrich', group: 'ratite', image: '',
    name: 'ダチョウ', en: 'Common Ostrich', sci: 'Struthio camelus',
    taxon: 'ダチョウ目ダチョウ科', region: 'アフリカ', size: '全長 2.0–2.8m',
    wiki: { ja: 'ダチョウ', en: 'Common ostrich' },
    note: '現生では世界最大の鳥。飛べないかわりに時速70kmで走り、足の指は2本しかない。',
  },
  {
    id: 'emu', group: 'ratite', image: '',
    name: 'エミュー', en: 'Emu', sci: 'Dromaius novaehollandiae',
    taxon: 'ヒクイドリ目エミュー科', region: 'オーストラリア', size: '全長 1.5–1.9m',
    wiki: { ja: 'エミュー', en: 'Emu' },
    note: 'ダチョウに次ぐ大きさ。ぼさぼさに見える羽は、1つの羽軸から2本の羽枝が生えるため。',
  },
  {
    id: 'cassowary', group: 'ratite', image: '',
    name: 'ヒクイドリ', en: 'Southern Cassowary', sci: 'Casuarius casuarius',
    taxon: 'ヒクイドリ目ヒクイドリ科', region: 'ニューギニア・豪州北東部', size: '全長 1.3–1.7m',
    wiki: { ja: 'ヒクイドリ', en: 'Southern cassowary' },
    note: '頭のヘルメット状の突起（カスク）と青い首。内側の爪は10cmを超え、蹴りは危険。',
  },
  {
    id: 'kiwi', group: 'ratite', image: '',
    name: 'キーウィ', en: 'Kiwi', sci: 'Apteryx spp.',
    taxon: 'キーウィ目キーウィ科', region: 'ニュージーランド', size: '全長 35–55cm',
    wiki: { ja: 'キーウィ', en: 'Kiwi (bird)' },
    note: 'ニワトリほどの大きさで翼はほぼ退化。鳥では例外的に嘴の先端に鼻孔があり、匂いで土中の餌を探す。',
  },
  {
    id: 'rhea', group: 'ratite', image: '',
    name: 'オオレア', en: 'Greater Rhea', sci: 'Rhea americana',
    taxon: 'レア目レア科', region: '南アメリカ', size: '全長 1.3–1.4m',
    wiki: { ja: 'オオレア', en: 'Greater rhea' },
    note: '南米版のダチョウ。オスが巣を作り、複数のメスが産んだ卵をまとめて抱く。',
  },

  // ── 地上を歩く鳥 ──────────────────────────────────────
  {
    id: 'greenpheasant', group: 'ground', image: '',
    name: 'キジ', en: 'Green Pheasant', sci: 'Phasianus versicolor',
    taxon: 'キジ目キジ科', region: '日本（固有種）', size: 'オス 全長 約80cm',
    wiki: { ja: 'キジ', en: 'Green pheasant' },
    note: '日本の国鳥。オスは緑色の体に赤い肉垂、長い尾。「ケーン」と鳴いて翼を打ち鳴らす。',
  },
  {
    id: 'peafowl', group: 'ground', image: '',
    name: 'インドクジャク', en: 'Indian Peafowl', sci: 'Pavo cristatus',
    taxon: 'キジ目キジ科', region: '南アジア', size: '上尾筒を含め 2m超',
    wiki: { ja: 'インドクジャク', en: 'Indian peafowl' },
    note: '広げる「羽根」は尾ではなく上尾筒。目玉模様は150枚以上ある。インドの国鳥。',
  },
  {
    id: 'ptarmigan', group: 'ground', image: '',
    name: 'ライチョウ', en: 'Rock Ptarmigan', sci: 'Lagopus muta',
    taxon: 'キジ目キジ科', region: '北半球の寒帯・高山', size: '全長 約37cm',
    wiki: { ja: 'ライチョウ', en: 'Rock ptarmigan' },
    note: '夏は褐色、冬は純白に換羽する。日本では本州中部の高山帯に隔離分布し、特別天然記念物。',
  },
  {
    id: 'guineafowl', group: 'ground', image: '',
    name: 'ホロホロチョウ', en: 'Helmeted Guineafowl', sci: 'Numida meleagris',
    taxon: 'キジ目ホロホロチョウ科', region: 'アフリカ', size: '全長 約55cm',
    wiki: { ja: 'ホロホロチョウ', en: 'Helmeted guineafowl' },
    note: '灰色に白い水玉模様、裸出した青い頭。家禽として世界に広まった。',
  },
  {
    id: 'turkey', group: 'ground', image: '',
    name: 'シチメンチョウ', en: 'Wild Turkey', sci: 'Meleagris gallopavo',
    taxon: 'キジ目キジ科', region: '北アメリカ', size: '全長 約1m',
    wiki: { ja: 'シチメンチョウ', en: 'Wild turkey' },
    note: '顔の裸出部が興奮すると赤・青・白と変わるのが「七面」の由来。胸から毛束状の羽が垂れる。',
  },
  {
    id: 'monal', group: 'ground', image: '',
    name: 'ニジキジ', en: 'Himalayan Monal', sci: 'Lophophorus impejanus',
    taxon: 'キジ目キジ科', region: 'ヒマラヤ', size: '全長 約70cm',
    wiki: { ja: 'ニジキジ', en: 'Himalayan monal' },
    note: '全身が金属光沢の虹色に輝く。ネパールの国鳥。',
  },
  {
    id: 'junglefowl', group: 'ground', image: '',
    name: 'セキショクヤケイ', en: 'Red Junglefowl', sci: 'Gallus gallus',
    taxon: 'キジ目キジ科', region: '東南アジア', size: '全長 約70cm',
    wiki: { ja: 'セキショクヤケイ', en: 'Red junglefowl' },
    note: 'ニワトリの原種。森の下生えで暮らし、飛ぶのは木に登るときくらい。',
  },
  {
    id: 'crownedpigeon', group: 'ground', image: '',
    name: 'カンムリバト', en: 'Victoria Crowned Pigeon', sci: 'Goura victoria',
    taxon: 'ハト目ハト科', region: 'ニューギニア', size: '全長 約74cm',
    wiki: { ja: 'カンムリバト', en: 'Victoria crowned pigeon' },
    note: 'レース状の冠羽をもつ世界最大級のハト。ほとんど地上を歩いて落果を食べる。',
  },

  // ── カモ・ハクチョウの仲間 ────────────────────────────
  {
    id: 'muteswan', group: 'waterfowl', image: '',
    name: 'コブハクチョウ', en: 'Mute Swan', sci: 'Cygnus olor',
    taxon: 'カモ目カモ科', region: 'ユーラシア', size: '全長 約1.5m',
    wiki: { ja: 'コブハクチョウ', en: 'Mute swan' },
    note: '橙色の嘴の付け根に黒いコブ。首をS字に曲げて泳ぐのが他のハクチョウとの違い。',
  },
  {
    id: 'blackswan', group: 'waterfowl', image: '',
    name: 'コクチョウ', en: 'Black Swan', sci: 'Cygnus atratus',
    taxon: 'カモ目カモ科', region: 'オーストラリア', size: '全長 1.2–1.4m',
    wiki: { ja: 'コクチョウ', en: 'Black swan' },
    note: '全身黒く嘴は赤。飛ぶと初列風切の白がはっきり現れる。西オーストラリア州の州鳥。',
  },
  {
    id: 'whooperswan', group: 'waterfowl', image: '',
    name: 'オオハクチョウ', en: 'Whooper Swan', sci: 'Cygnus cygnus',
    taxon: 'カモ目カモ科', region: 'ユーラシア北部', size: '全長 約1.4m',
    wiki: { ja: 'オオハクチョウ', en: 'Whooper swan' },
    note: '嘴の黄色部分が前方に尖って伸びる。日本には冬鳥として渡来する。フィンランドの国鳥。',
  },
  {
    id: 'mandarin', group: 'waterfowl', image: '',
    name: 'オシドリ', en: 'Mandarin Duck', sci: 'Aix galericulata',
    taxon: 'カモ目カモ科', region: '東アジア', size: '全長 約45cm',
    wiki: { ja: 'オシドリ', en: 'Mandarin duck' },
    note: 'オスの橙色の帆のような「銀杏羽」。仲睦まじさの代名詞だが、実際は毎年つがい相手が変わる。',
  },
  {
    id: 'mallard', group: 'waterfowl', image: '',
    name: 'マガモ', en: 'Mallard', sci: 'Anas platyrhynchos',
    taxon: 'カモ目カモ科', region: '北半球全域', size: '全長 約60cm',
    wiki: { ja: 'マガモ', en: 'Mallard' },
    note: 'オスの頭は緑の光沢、首に白い輪。アヒルやアオクビアヒルの原種。',
  },
  {
    id: 'canadagoose', group: 'waterfowl', image: '',
    name: 'カナダガン', en: 'Canada Goose', sci: 'Branta canadensis',
    taxon: 'カモ目カモ科', region: '北アメリカ', size: '全長 90cm–1m',
    wiki: { ja: 'カナダガン', en: 'Canada goose' },
    note: '黒い首と頭に白い頬のライン。V字編隊で長距離を渡る。',
  },
  {
    id: 'snowgoose', group: 'waterfowl', image: '',
    name: 'ハクガン', en: 'Snow Goose', sci: 'Anser caerulescens',
    taxon: 'カモ目カモ科', region: '北アメリカ・シベリア', size: '全長 約70cm',
    wiki: { ja: 'ハクガン', en: 'Snow goose' },
    note: '白い体に黒い翼の先。ツンドラで繁殖し、数万羽の群れで渡る。',
  },
  {
    id: 'grebe', group: 'waterfowl', image: '',
    name: 'カンムリカイツブリ', en: 'Great Crested Grebe', sci: 'Podiceps cristatus',
    taxon: 'カイツブリ目カイツブリ科', region: 'ユーラシア・アフリカ・豪州', size: '全長 約50cm',
    wiki: { ja: 'カンムリカイツブリ', en: 'Great crested grebe' },
    note: '繁殖期は顔に襟飾りのような羽が出る。水面で向き合い水草をくわえて踊る求愛で有名。',
  },

  // ── ペンギン ──────────────────────────────────────────
  {
    id: 'emperorpenguin', group: 'penguin', image: '',
    name: 'コウテイペンギン', en: 'Emperor Penguin', sci: 'Aptenodytes forsteri',
    taxon: 'ペンギン目ペンギン科', region: '南極大陸', size: '全長 約1.2m',
    wiki: { ja: 'コウテイペンギン', en: 'Emperor penguin' },
    note: '現生最大のペンギン。真冬の南極で、オスが卵を足の上に乗せ約2か月絶食して温める。',
  },
  {
    id: 'kingpenguin', group: 'penguin', image: '',
    name: 'オウサマペンギン', en: 'King Penguin', sci: 'Aptenodytes patagonicus',
    taxon: 'ペンギン目ペンギン科', region: '亜南極の島々', size: '全長 約95cm',
    wiki: { ja: 'オウサマペンギン', en: 'King penguin' },
    note: 'コウテイペンギンに似るがひと回り小さく、耳のオレンジ色が濃く輪郭がはっきりしている。',
  },
  {
    id: 'gentoo', group: 'penguin', image: '',
    name: 'ジェンツーペンギン', en: 'Gentoo Penguin', sci: 'Pygoscelis papua',
    taxon: 'ペンギン目ペンギン科', region: '南極半島・亜南極', size: '全長 約80cm',
    wiki: { ja: 'ジェンツーペンギン', en: 'Gentoo penguin' },
    note: '目の上をつなぐ白い帯と橙色の嘴。泳ぐ速さは時速35kmでペンギン最速。',
  },
  {
    id: 'rockhopper', group: 'penguin', image: '',
    name: 'イワトビペンギン', en: 'Southern Rockhopper Penguin', sci: 'Eudyptes chrysocome',
    taxon: 'ペンギン目ペンギン科', region: '亜南極の島々', size: '全長 約55cm',
    wiki: { ja: 'イワトビペンギン', en: 'Southern rockhopper penguin' },
    note: '黄色い眉のような飾り羽と赤い目。名のとおり両足を揃えて岩場を跳ねて登る。',
  },
  {
    id: 'africanpenguin', group: 'penguin', image: '',
    name: 'ケープペンギン', en: 'African Penguin', sci: 'Spheniscus demersus',
    taxon: 'ペンギン目ペンギン科', region: '南アフリカ沿岸', size: '全長 約65cm',
    wiki: { ja: 'ケープペンギン', en: 'African penguin' },
    note: '胸の黒いU字の帯と目の上のピンクの裸出部。ロバに似た声から jackass penguin とも。',
  },

  // ── 海鳥 ──────────────────────────────────────────────
  {
    id: 'wanderingalbatross', group: 'seabird', image: '',
    name: 'ワタリアホウドリ', en: 'Wandering Albatross', sci: 'Diomedea exulans',
    taxon: 'ミズナギドリ目アホウドリ科', region: '南大洋', size: '翼開長 最大 3.5m',
    wiki: { ja: 'ワタリアホウドリ', en: 'Wandering albatross' },
    note: '現生鳥類で最大の翼開長。ほとんど羽ばたかず、風を使った滑翔で南極海を一周する。',
  },
  {
    id: 'albatross', group: 'seabird', image: '',
    name: 'アホウドリ', en: 'Short-tailed Albatross', sci: 'Phoebastria albatrus',
    taxon: 'ミズナギドリ目アホウドリ科', region: '北太平洋', size: '全長 約90cm',
    wiki: { ja: 'アホウドリ', en: 'Short-tailed albatross' },
    note: '羽毛採取で一度は絶滅寸前に。伊豆諸島の鳥島や尖閣諸島で個体数が回復しつつある。',
  },
  {
    id: 'puffin', group: 'seabird', image: '',
    name: 'ニシツノメドリ', en: 'Atlantic Puffin', sci: 'Fratercula arctica',
    taxon: 'チドリ目ウミスズメ科', region: '北大西洋', size: '全長 約30cm',
    wiki: { ja: 'ニシツノメドリ', en: 'Atlantic puffin' },
    note: '繁殖期だけ嘴が赤・黄・青の極彩色になる。小魚を十数匹きれいに並べて嘴で運ぶ。',
  },
  {
    id: 'tuftedpuffin', group: 'seabird', image: '',
    name: 'エトピリカ', en: 'Tufted Puffin', sci: 'Fratercula cirrhata',
    taxon: 'チドリ目ウミスズメ科', region: '北太平洋', size: '全長 約38cm',
    wiki: { ja: 'エトピリカ', en: 'Tufted puffin' },
    note: '繁殖期に後頭から金色の房状の飾り羽が垂れる。名はアイヌ語で「嘴が美しい」。',
  },
  {
    id: 'booby', group: 'seabird', image: '',
    name: 'アオアシカツオドリ', en: 'Blue-footed Booby', sci: 'Sula nebouxii',
    taxon: 'カツオドリ目カツオドリ科', region: '東太平洋・ガラパゴス', size: '全長 約80cm',
    wiki: { ja: 'アオアシカツオドリ', en: 'Blue-footed booby' },
    note: '水色の足を交互に持ち上げて見せる求愛ダンス。足の青が濃いほど健康の証とされる。',
  },
  {
    id: 'frigatebird', group: 'seabird', image: '',
    name: 'オオグンカンドリ', en: 'Great Frigatebird', sci: 'Fregata minor',
    taxon: 'カツオドリ目グンカンドリ科', region: '熱帯の海洋', size: '全長 約1m',
    wiki: { ja: 'オオグンカンドリ', en: 'Great frigatebird' },
    note: 'オスは赤い喉袋を風船のように膨らませる。他の海鳥を追い回して獲物を奪う「海賊」。',
  },
  {
    id: 'pelican', group: 'seabird', image: '',
    name: 'モモイロペリカン', en: 'Great White Pelican', sci: 'Pelecanus onocrotalus',
    taxon: 'ペリカン目ペリカン科', region: 'アフリカ・南欧・西アジア', size: '全長 約1.6m',
    wiki: { ja: 'モモイロペリカン', en: 'Great white pelican' },
    note: '喉袋で水ごと魚をすくい、水を吐き出してから飲み込む。集団で半円に並んで追い込み漁をする。',
  },

  // ── 水辺の大型鳥 ──────────────────────────────────────
  {
    id: 'redcrownedcrane', group: 'wader', image: '',
    name: 'タンチョウ', en: 'Red-crowned Crane', sci: 'Grus japonensis',
    taxon: 'ツル目ツル科', region: '東アジア', size: '全長 約1.4m',
    wiki: { ja: 'タンチョウ', en: 'Red-crowned crane' },
    note: '頭頂の赤は羽毛ではなく裸出した皮膚。北海道の釧路湿原に周年生息する群れがいる。',
  },
  {
    id: 'crownedcrane', group: 'wader', image: '',
    name: 'ホオジロカンムリヅル', en: 'Grey Crowned Crane', sci: 'Balearica regulorum',
    taxon: 'ツル目ツル科', region: 'アフリカ東部・南部', size: '全長 約1m',
    wiki: { ja: 'ホオジロカンムリヅル', en: 'Grey crowned crane' },
    note: '金色の針状の冠羽と白い頬。ウガンダの国鳥で、国旗の中央にも描かれている。',
  },
  {
    id: 'orientalstork', group: 'wader', image: '',
    name: 'コウノトリ', en: 'Oriental Stork', sci: 'Ciconia boyciana',
    taxon: 'コウノトリ目コウノトリ科', region: '東アジア', size: '全長 約1.1m',
    wiki: { ja: 'コウノトリ', en: 'Oriental stork' },
    note: '嘴が黒く、目の周りが赤い。日本では1971年に野生絶滅し、兵庫県豊岡市で再導入が進む。',
  },
  {
    id: 'whitestork', group: 'wader', image: '',
    name: 'シュバシコウ', en: 'White Stork', sci: 'Ciconia ciconia',
    taxon: 'コウノトリ目コウノトリ科', region: 'ヨーロッパ・北アフリカ', size: '全長 約1m',
    wiki: { ja: 'シュバシコウ', en: 'White stork' },
    note: '名のとおり朱色の嘴。ヨーロッパで「赤ちゃんを運ぶ鳥」とされ、屋根の上に巣を作る。',
  },
  {
    id: 'shoebill', group: 'wader', image: '',
    name: 'ハシビロコウ', en: 'Shoebill', sci: 'Balaeniceps rex',
    taxon: 'ペリカン目ハシビロコウ科', region: '中央アフリカの湿地', size: '全長 約1.2m',
    wiki: { ja: 'ハシビロコウ', en: 'Shoebill' },
    note: '木靴のような巨大な嘴。何時間も微動だにせず、水面に呼吸に来るハイギョを待ち伏せる。',
  },
  {
    id: 'marabou', group: 'wader', image: '',
    name: 'アフリカハゲコウ', en: 'Marabou Stork', sci: 'Leptoptilos crumenifer',
    taxon: 'コウノトリ目コウノトリ科', region: 'サハラ以南のアフリカ', size: '全長 約1.5m',
    wiki: { ja: 'アフリカハゲコウ', en: 'Marabou stork' },
    note: '裸の頭と喉から垂れる肉垂。翼開長は3m近く、腐肉を食べる「掃除屋」として働く。',
  },
  {
    id: 'scarletibis', group: 'wader', image: '',
    name: 'ショウジョウトキ', en: 'Scarlet Ibis', sci: 'Eudocimus ruber',
    taxon: 'ペリカン目トキ科', region: '南アメリカ北部', size: '全長 約60cm',
    wiki: { ja: 'ショウジョウトキ', en: 'Scarlet ibis' },
    note: '甲殻類に含まれる色素で全身が緋色に染まる。トリニダード・トバゴの国鳥。',
  },
  {
    id: 'crestedibis', group: 'wader', image: '',
    name: 'トキ', en: 'Crested Ibis', sci: 'Nipponia nippon',
    taxon: 'ペリカン目トキ科', region: '東アジア', size: '全長 約75cm',
    wiki: { ja: 'トキ', en: 'Crested ibis' },
    note: '学名は Nipponia nippon。翼の内側の淡紅色を「朱鷺色」と呼ぶ。日本産は2003年に絶滅した。',
  },
  {
    id: 'flamingo', group: 'wader', image: '',
    name: 'オオフラミンゴ', en: 'Greater Flamingo', sci: 'Phoenicopterus roseus',
    taxon: 'フラミンゴ目フラミンゴ科', region: 'アフリカ・南欧・南アジア', size: '全長 約1.4m',
    wiki: { ja: 'オオフラミンゴ', en: 'Greater flamingo' },
    note: '嘴を上下逆さにして水中の藻類や小動物を濾しとる。ピンク色は餌のカロテノイド由来。',
  },
  {
    id: 'greyheron', group: 'wader', image: '',
    name: 'アオサギ', en: 'Grey Heron', sci: 'Ardea cinerea',
    taxon: 'ペリカン目サギ科', region: 'ユーラシア・アフリカ', size: '全長 約95cm',
    wiki: { ja: 'アオサギ', en: 'Grey heron' },
    note: '日本最大級のサギ。ツルと違い、飛ぶときは首をS字に畳んで足を後ろへ伸ばす。',
  },
  {
    id: 'okinawarail', group: 'wader', image: '',
    name: 'ヤンバルクイナ', en: 'Okinawa Rail', sci: 'Hypotaenidia okinawae',
    taxon: 'ツル目クイナ科', region: '沖縄島北部（やんばる）', size: '全長 約30cm',
    wiki: { ja: 'ヤンバルクイナ', en: 'Okinawa rail' },
    note: '1981年に新種として記載された日本唯一の飛べないクイナ。赤い嘴と脚、脇の白黒縞。',
  },

  // ── 猛禽類 ────────────────────────────────────────────
  {
    id: 'baldeagle', group: 'raptor', image: '',
    name: 'ハクトウワシ', en: 'Bald Eagle', sci: 'Haliaeetus leucocephalus',
    taxon: 'タカ目タカ科', region: '北アメリカ', size: '翼開長 約2m',
    wiki: { ja: 'ハクトウワシ', en: 'Bald eagle' },
    note: 'アメリカ合衆国の国鳥。頭と尾が白くなるのは4–5歳の成鳥から。魚を主食にする。',
  },
  {
    id: 'stellerseaeagle', group: 'raptor', image: '',
    name: 'オオワシ', en: "Steller's Sea Eagle", sci: 'Haliaeetus pelagicus',
    taxon: 'タカ目タカ科', region: 'オホーツク海沿岸', size: '翼開長 約2.4m',
    wiki: { ja: 'オオワシ', en: "Steller's sea eagle" },
    note: '巨大な黄色い嘴と、肩・尾の白。世界で最も重いワシの一つで、冬に北海道へ渡来する。',
  },
  {
    id: 'goldeneagle', group: 'raptor', image: '',
    name: 'イヌワシ', en: 'Golden Eagle', sci: 'Aquila chrysaetos',
    taxon: 'タカ目タカ科', region: '北半球', size: '翼開長 約2m',
    wiki: { ja: 'イヌワシ', en: 'Golden eagle' },
    note: '後頭部の羽が金褐色に光る。日本では山地に500羽ほどしかいないとされる。',
  },
  {
    id: 'peregrine', group: 'raptor', image: '',
    name: 'ハヤブサ', en: 'Peregrine Falcon', sci: 'Falco peregrinus',
    taxon: 'ハヤブサ目ハヤブサ科', region: '南極を除く全大陸', size: '全長 約50cm',
    wiki: { ja: 'ハヤブサ', en: 'Peregrine falcon' },
    note: '獲物へ急降下するときの速度は時速300kmを超え、動物界で最速。目の下の黒い「頬髭」が特徴。',
  },
  {
    id: 'osprey', group: 'raptor', image: '',
    name: 'ミサゴ', en: 'Osprey', sci: 'Pandion haliaetus',
    taxon: 'タカ目ミサゴ科', region: 'ほぼ全世界', size: '全長 約60cm',
    wiki: { ja: 'ミサゴ', en: 'Osprey' },
    note: '足裏のトゲと前後に回る外側の指で、滑る魚をしっかりつかむ。水面に足から突っ込んで狩る。',
  },
  {
    id: 'secretarybird', group: 'raptor', image: '',
    name: 'ヘビクイワシ', en: 'Secretarybird', sci: 'Sagittarius serpentarius',
    taxon: 'タカ目ヘビクイワシ科', region: 'サハラ以南のアフリカ', size: '全長 約1.3m',
    wiki: { ja: 'ヘビクイワシ', en: 'Secretarybird' },
    note: 'ツルのような長い脚で草原を歩き回り、体重の5倍以上の力の蹴りでヘビを仕留める。',
  },
  {
    id: 'andeancondor', group: 'raptor', image: '',
    name: 'アンデスコンドル', en: 'Andean Condor', sci: 'Vultur gryphus',
    taxon: 'コンドル目コンドル科', region: 'アンデス山脈', size: '翼開長 約3.2m',
    wiki: { ja: 'アンデスコンドル', en: 'Andean condor' },
    note: '陸鳥では最大級の翼。上昇気流に乗り、5時間以上ほとんど羽ばたかずに飛んだ記録がある。',
  },
  {
    id: 'beardedvulture', group: 'raptor', image: '',
    name: 'ヒゲワシ', en: 'Bearded Vulture', sci: 'Gypaetus barbatus',
    taxon: 'タカ目タカ科', region: 'ユーラシア・アフリカの山岳', size: '翼開長 約2.8m',
    wiki: { ja: 'ヒゲワシ', en: 'Bearded vulture' },
    note: '食物の大半が骨。岩場の上空から落として割り、骨髄を食べる。鉄分を含む土で羽を橙色に染める。',
  },
  {
    id: 'harpyeagle', group: 'raptor', image: '',
    name: 'オウギワシ', en: 'Harpy Eagle', sci: 'Harpia harpyja',
    taxon: 'タカ目タカ科', region: '中南米の熱帯林', size: '全長 約1m',
    wiki: { ja: 'オウギワシ', en: 'Harpy eagle' },
    note: '世界最強クラスの猛禽。後ろの爪はヒグマの爪より長く、樹上のナマケモノやサルを襲う。',
  },

  // ── フクロウ類 ────────────────────────────────────────
  {
    id: 'snowyowl', group: 'owl', image: '',
    name: 'シロフクロウ', en: 'Snowy Owl', sci: 'Bubo scandiacus',
    taxon: 'フクロウ目フクロウ科', region: '北極圏のツンドラ', size: '全長 約60cm',
    wiki: { ja: 'シロフクロウ', en: 'Snowy owl' },
    note: 'オスは加齢とともにほぼ純白に。白夜の北極圏では昼にも狩りをし、レミングを主食にする。',
  },
  {
    id: 'barnowl', group: 'owl', image: '',
    name: 'メンフクロウ', en: 'Barn Owl', sci: 'Tyto alba',
    taxon: 'フクロウ目メンフクロウ科', region: 'ほぼ全世界', size: '全長 約35cm',
    wiki: { ja: 'メンフクロウ', en: 'Barn owl' },
    note: 'ハート型の白い顔盤がパラボラのように音を集め、左右非対称な耳で獲物の位置を立体的に捉える。',
  },
  {
    id: 'eagleowl', group: 'owl', image: '',
    name: 'ワシミミズク', en: 'Eurasian Eagle-Owl', sci: 'Bubo bubo',
    taxon: 'フクロウ目フクロウ科', region: 'ユーラシア', size: '全長 約70cm',
    wiki: { ja: 'ワシミミズク', en: 'Eurasian eagle-owl' },
    note: 'フクロウ類最大級。燃えるような橙色の目と、耳のように立つ長い羽角。',
  },
  {
    id: 'greathornedowl', group: 'owl', image: '',
    name: 'アメリカワシミミズク', en: 'Great Horned Owl', sci: 'Bubo virginianus',
    taxon: 'フクロウ目フクロウ科', region: '南北アメリカ', size: '全長 約55cm',
    wiki: { ja: 'アメリカワシミミズク', en: 'Great horned owl' },
    note: '黄色い目と大きな羽角。スカンクさえ襲う南北アメリカで最も広く分布する大型フクロウ。',
  },

  // ── インコ・オウム類 ──────────────────────────────────
  {
    id: 'scarletmacaw', group: 'parrot', image: '',
    name: 'コンゴウインコ', en: 'Scarlet Macaw', sci: 'Ara macao',
    taxon: 'オウム目インコ科', region: '中南米の熱帯林', size: '全長 約85cm',
    wiki: { ja: 'コンゴウインコ', en: 'Scarlet macaw' },
    note: '赤地に黄と青のグラデーション。全長の半分以上を長い尾が占める。',
  },
  {
    id: 'bluemacaw', group: 'parrot', image: '',
    name: 'ルリコンゴウインコ', en: 'Blue-and-yellow Macaw', sci: 'Ara ararauna',
    taxon: 'オウム目インコ科', region: '南アメリカ', size: '全長 約85cm',
    wiki: { ja: 'ルリコンゴウインコ', en: 'Blue-and-yellow macaw' },
    note: '背が青、腹が黄色。顔の白い裸出部に走る細い黒線の模様は個体ごとに違う。',
  },
  {
    id: 'greyparrot', group: 'parrot', image: '',
    name: 'ヨウム', en: 'Grey Parrot', sci: 'Psittacus erithacus',
    taxon: 'オウム目インコ科', region: '中央アフリカ', size: '全長 約33cm',
    wiki: { ja: 'ヨウム', en: 'Grey parrot' },
    note: '灰色の体に真っ赤な尾。言葉を状況に合わせて使う知能で知られ、5歳児並みとも言われる。',
  },
  {
    id: 'cockatoo', group: 'parrot', image: '',
    name: 'キバタン', en: 'Sulphur-crested Cockatoo', sci: 'Cacatua galerita',
    taxon: 'オウム目オウム科', region: 'オーストラリア・ニューギニア', size: '全長 約50cm',
    wiki: { ja: 'キバタン', en: 'Sulphur-crested cockatoo' },
    note: '白い体に、興奮すると扇状に開く黄色い冠羽。都市部でゴミ箱の蓋を開ける行動が話題になった。',
  },
  {
    id: 'budgerigar', group: 'parrot', image: '',
    name: 'セキセイインコ', en: 'Budgerigar', sci: 'Melopsittacus undulatus',
    taxon: 'オウム目インコ科', region: 'オーストラリア内陸', size: '全長 約18cm',
    wiki: { ja: 'セキセイインコ', en: 'Budgerigar' },
    note: '野生では黄緑に黒の細かな波模様のみ。乾燥地を数万羽の群れで移動する。',
  },
  {
    id: 'kea', group: 'parrot', image: '',
    name: 'ミヤマオウム', en: 'Kea', sci: 'Nestor notabilis',
    taxon: 'オウム目フクロウオウム科', region: 'ニュージーランド南島', size: '全長 約48cm',
    wiki: { ja: 'ミヤマオウム', en: 'Kea' },
    note: '世界で唯一の高山性オウム。地味なオリーブ色だが翼の裏だけ鮮やかな橙。道具を使う知能で有名。',
  },

  // ── 森の色鳥 ──────────────────────────────────────────
  {
    id: 'kingfisher', group: 'colorful', image: '',
    name: 'カワセミ', en: 'Common Kingfisher', sci: 'Alcedo atthis',
    taxon: 'ブッポウソウ目カワセミ科', region: 'ユーラシア・北アフリカ', size: '全長 約17cm',
    wiki: { ja: 'カワセミ', en: 'Common kingfisher' },
    note: '「飛ぶ宝石」。背の青は色素ではなく羽の微細構造が光を干渉させて生む構造色。',
  },
  {
    id: 'ruddykingfisher', group: 'colorful', image: '',
    name: 'アカショウビン', en: 'Ruddy Kingfisher', sci: 'Halcyon coromanda',
    taxon: 'ブッポウソウ目カワセミ科', region: '東アジア・東南アジア', size: '全長 約27cm',
    wiki: { ja: 'アカショウビン', en: 'Ruddy kingfisher' },
    note: '全身が赤褐色で嘴も赤い。日本には夏鳥として渡来し「キョロロロロ…」と鳴く。',
  },
  {
    id: 'roller', group: 'colorful', image: '',
    name: 'ライラックニシブッポウソウ', en: 'Lilac-breasted Roller', sci: 'Coracias caudatus',
    taxon: 'ブッポウソウ目ブッポウソウ科', region: 'サハラ以南のアフリカ', size: '全長 約36cm',
    wiki: { ja: 'ライラックニシブッポウソウ', en: 'Lilac-breasted roller' },
    note: '胸のライラック色と、飛ぶと現れる濃淡の青。求愛時に空中で横転する飛び方が名の由来。',
  },
  {
    id: 'beeeater', group: 'colorful', image: '',
    name: 'ヨーロッパハチクイ', en: 'European Bee-eater', sci: 'Merops apiaster',
    taxon: 'ブッポウソウ目ハチクイ科', region: '南欧・西アジア・アフリカ', size: '全長 約28cm',
    wiki: { ja: 'ヨーロッパハチクイ', en: 'European bee-eater' },
    note: '捕らえたハチを枝に叩きつけ、毒針をしごき出してから飲み込む。崖に穴を掘って営巣する。',
  },
  {
    id: 'hoopoe', group: 'colorful', image: '',
    name: 'ヤツガシラ', en: 'Eurasian Hoopoe', sci: 'Upupa epops',
    taxon: 'サイチョウ目ヤツガシラ科', region: 'ユーラシア・アフリカ', size: '全長 約28cm',
    wiki: { ja: 'ヤツガシラ', en: 'Eurasian hoopoe' },
    note: '広げると扇になる冠羽と白黒の縞の翼。日本では春秋にまれに現れる旅鳥。イスラエルの国鳥。',
  },
  {
    id: 'toucan', group: 'colorful', image: '',
    name: 'オニオオハシ', en: 'Toco Toucan', sci: 'Ramphastos toco',
    taxon: 'キツツキ目オオハシ科', region: '南アメリカ', size: '全長 約60cm',
    wiki: { ja: 'オニオオハシ', en: 'Toco toucan' },
    note: '体長の3分の1を占める嘴は内部がスポンジ状で軽く、体温を逃がす放熱器官でもある。',
  },
  {
    id: 'hornbill', group: 'colorful', image: '',
    name: 'サイチョウ', en: 'Great Hornbill', sci: 'Buceros bicornis',
    taxon: 'サイチョウ目サイチョウ科', region: '南アジア・東南アジア', size: '全長 約1.2m',
    wiki: { ja: 'サイチョウ', en: 'Great hornbill' },
    note: '嘴の上に載る角状のカスク。メスは樹洞に入って泥で入口を塗り固め、中で子育てする。',
  },
  {
    id: 'quetzal', group: 'colorful', image: '',
    name: 'カザリキヌバネドリ', en: 'Resplendent Quetzal', sci: 'Pharomachrus mocinno',
    taxon: 'キヌバネドリ目キヌバネドリ科', region: '中央アメリカの雲霧林', size: '尾を含め 1m超',
    wiki: { ja: 'カザリキヌバネドリ', en: 'Resplendent quetzal' },
    note: 'マヤ・アステカの聖鳥。オスの上尾筒は60cmを超えて垂れる。グアテマラの国鳥で通貨の名にもなった。',
  },
  {
    id: 'beehummingbird', group: 'colorful', image: '',
    name: 'マメハチドリ', en: 'Bee Hummingbird', sci: 'Mellisuga helenae',
    taxon: 'アマツバメ目ハチドリ科', region: 'キューバ', size: '全長 5–6cm',
    wiki: { ja: 'マメハチドリ', en: 'Bee hummingbird' },
    note: '世界最小の鳥。体重は約2gで1円玉2枚ほど。毎秒80回羽ばたき、空中に静止して蜜を吸う。',
  },
  {
    id: 'birdofparadise', group: 'colorful', image: '',
    name: 'オオフウチョウ', en: 'Greater Bird-of-paradise', sci: 'Paradisaea apoda',
    taxon: 'スズメ目フウチョウ科', region: 'ニューギニア', size: '全長 約43cm',
    wiki: { ja: 'オオフウチョウ', en: 'Greater bird-of-paradise' },
    note: 'オスの脇から噴き出す黄色い飾り羽。学名 apoda（足なし）は、足を切って交易された標本に由来する。',
  },
  {
    id: 'blackwoodpecker', group: 'colorful', image: '',
    name: 'クマゲラ', en: 'Black Woodpecker', sci: 'Dryocopus martius',
    taxon: 'キツツキ目キツツキ科', region: 'ユーラシア北部', size: '全長 約45cm',
    wiki: { ja: 'クマゲラ', en: 'Black woodpecker' },
    note: '日本最大のキツツキ。全身黒く頭頂だけ赤い。北海道と東北の一部にのみ生息し天然記念物。',
  },

  // ── スズメ目の鳥 ──────────────────────────────────────
  {
    id: 'bluejay', group: 'songbird', image: '',
    name: 'アオカケス', en: 'Blue Jay', sci: 'Cyanocitta cristata',
    taxon: 'スズメ目カラス科', region: '北アメリカ東部', size: '全長 約28cm',
    wiki: { ja: 'アオカケス', en: 'Blue jay' },
    note: '青い冠羽と黒い首輪。タカの鳴き声を真似て他の鳥を追い払うことがある。',
  },
  {
    id: 'robin', group: 'songbird', image: '',
    name: 'ヨーロッパコマドリ', en: 'European Robin', sci: 'Erithacus rubecula',
    taxon: 'スズメ目ヒタキ科', region: 'ヨーロッパ', size: '全長 約14cm',
    wiki: { ja: 'ヨーロッパコマドリ', en: 'European robin' },
    note: '顔から胸にかけての橙色。イギリスで最も愛される鳥とされ、クリスマスカードの常連。',
  },
  {
    id: 'magpie', group: 'songbird', image: '',
    name: 'カササギ', en: 'Eurasian Magpie', sci: 'Pica pica',
    taxon: 'スズメ目カラス科', region: 'ユーラシア', size: '全長 約45cm',
    wiki: { ja: 'カササギ', en: 'Eurasian magpie' },
    note: '白黒に見えるが翼と尾は青緑の光沢。鏡に映る姿を自分と認識できる数少ない鳥の一つ。',
  },
  {
    id: 'bowerbird', group: 'songbird', image: '',
    name: 'アオアズマヤドリ', en: 'Satin Bowerbird', sci: 'Ptilonorhynchus violaceus',
    taxon: 'スズメ目ニワシドリ科', region: 'オーストラリア東部', size: '全長 約30cm',
    wiki: { ja: 'アオアズマヤドリ', en: 'Satin bowerbird' },
    note: 'オスは小枝であずまや（バワー）を建て、青い花やペットボトルの蓋を集めて飾り立てる。',
  },
  {
    id: 'lyrebird', group: 'songbird', image: '',
    name: 'コトドリ', en: 'Superb Lyrebird', sci: 'Menura novaehollandiae',
    taxon: 'スズメ目コトドリ科', region: 'オーストラリア南東部', size: '尾を含め 約1m',
    wiki: { ja: 'コトドリ', en: 'Superb lyrebird' },
    note: '竪琴の形に広がる尾。他の鳥の声だけでなく、チェーンソーやカメラのシャッター音まで模倣する。',
  },
  {
    id: 'cardinal', group: 'songbird', image: '',
    name: 'ショウジョウコウカンチョウ', en: 'Northern Cardinal', sci: 'Cardinalis cardinalis',
    taxon: 'スズメ目ショウジョウコウカンチョウ科', region: '北アメリカ東部', size: '全長 約22cm',
    wiki: { ja: 'ショウジョウコウカンチョウ', en: 'Northern cardinal' },
    note: 'オスは全身赤に黒い顔と尖った冠羽。アメリカで7つの州の州鳥に選ばれている。',
  },
  {
    id: 'swallow', group: 'songbird', image: '',
    name: 'ツバメ', en: 'Barn Swallow', sci: 'Hirundo rustica',
    taxon: 'スズメ目ツバメ科', region: '北半球で繁殖・南半球で越冬', size: '全長 約17cm',
    wiki: { ja: 'ツバメ', en: 'Barn swallow' },
    note: '人家の軒先に泥と枯草の巣を作る。日本で繁殖した個体は東南アジアまで数千kmを渡る。',
  },
];
